In [1]:
import torch

## Creating Tensor

In [3]:
torch.rand(2,2)

tensor([[0.9161, 0.3453],
        [0.0102, 0.1069]])

In [10]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
x[0,0] = 10
x

tensor([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])

In [12]:
x[0][1] = 20
x

tensor([[10, 20,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])

In [13]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [15]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [19]:
torch.rand(1).item()

0.44970637559890747

## Device

In [20]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [25]:
mps_tensor = torch.rand(2).to("mps") # torch.rand(2, device="mps")
mps_tensor.device

device(type='mps', index=0)

## Tensor Method

In [34]:
x = torch.tensor([[2,4,3], [1,5,6], [7,9,8]])
x

tensor([[2, 4, 3],
        [1, 5, 6],
        [7, 9, 8]])

In [35]:
x.max()

tensor(9)

In [36]:
x.argmax()

tensor(7)

## Type Conversion

In [37]:
x.type()

'torch.LongTensor'

In [38]:
float_x = x.to(dtype=torch.float32)
float_x.type()

'torch.FloatTensor'

## Reshaping Tensors

In [42]:
flat_tensor = torch.rand(784)
flat_tensor.shape

torch.Size([784])

In [43]:
flat_tensor.view(1,28,28).shape

torch.Size([1, 28, 28])

In [44]:
flat_tensor.reshape(1, 28, 28).shape

torch.Size([1, 28, 28])

## Reordering Tensor

In [53]:
hwc_tensor = torch.rand(640, 480, 3)
hwc_tensor.shape

torch.Size([640, 480, 3])

In [54]:
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])